version: '3'
services:
  ### Postgres database for mcsv-inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:14-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcsv_inventory
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### MySQL database for mcsv-orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mcsv_orders
      MYSQL_USER: cessadev
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    expose:
      - 3307

  ### Postgres database for mcsv-products
  db-products:
    container_name: db-products
    image: postgres:14-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcsv_products
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433