version: '3.8'
services:
  ### Postgres database for mcsv-inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcsv_inventory
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### MySQL database for mcsv-orders
  db-orders:
    container_name: db-orders
    image: mysql:8.4.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_orders
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

  ### Postgres database for mcsv-products
  db-products:
    container_name: db-products
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcsv_products
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ### Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: cessadev
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5435
    expose:
      - 5435
    command: -p 5435

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5435
      DB_USER: cessadev
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  mysql_data: